version: '3.7'
services:
    minio:
        image: minio/minio
        ports:
            - "9000:9000"
        # volumes:
        #     - ./miniodata:/data
        environment:
            MINIO_ACCESS_KEY: ${V_MINIO_ACCESS_KEY}
            MINIO_SECRET_KEY: ${V_MINIO_SECRET_KEY}
        command: server /data

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=${V_POSTGRES_USER}
            - POSTGRES_PASSWORD=${V_POSTGRES_PASSWORD}
            - POSTGRES_DB=${V_POSTGRES_DB}
        # Uncomment these lines to persist data on the local filesystem.
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./pgdata:/var/lib/postgresql/data/pgdata

    webserver:
        image: saumalya75/airflowoncontainer:latest
        restart: always
        depends_on:
            - postgres
            - minio
        environment:
            - LOAD_EX=${V_LOAD_EX}
            - FERNET_KEY=${V_FERNET_KEY}
            - EXECUTOR=Local
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=${V_POSTGRES_PORT}
            - POSTGRES_USER=${V_POSTGRES_USER}
            - POSTGRES_PASSWORD=${V_POSTGRES_PASSWORD}
            - POSTGRES_DB=${V_POSTGRES_DB}
            - MINIO_ACCESS_KEY=${V_MINIO_ACCESS_KEY}
            - MINIO_SECRET_KEY=${V_MINIO_SECRET_KEY}
            - AWS_ACCESS_KEY_ID=${V_AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${V_AWS_SECRET_ACCESS_KEY}
        volumes:
            - ./airflow_home:/usr/local/airflow
            - ./app_home:/usr/local/app
            - ./app_home/independent_plugins:/usr/local/airflow/dags/independent_plugins
            - ./script_home:/usr/local/script
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
